

const AllCartsApi = [
    {
        id:1,
        rate:3.9,
        color:"Black",
        rated_Person:2001,
        category:"t-shirt",
        occucation:"Weddings",
        size:"S",
        best:false,
        price:"28",
        oldPrice:"$43",
        title:"Wedding Shirts blue Color.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (1).jpeg",
        off:"40% off",
    },
    {
        id:2,
        rate:3.8,
        color:"Gray",
        rated_Person:2031,
        category:"t-shirt",
        occucation:"Weddings",
        size:"M",
        best:true,
        price:"20",
        oldPrice:"$40",
        title:"Amul T-shirt in best price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (11).jpeg",
        off:"30% off",
    },
    {
        id:3,
        rate:4.3,
        color:"Red",
        rated_Person:2003,
        category:"t-shirt",
        occucation:"Weddings",
        size:"L",
        best:true,
        price:"60",
        oldPrice:"$120",
        title:"Levis Shirt American Standard.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (13).jpeg",
        off:"20% off",
    }, 
    {
        id:4,
        rate:3.3,
        color:"Blue",
        rated_Person:2231,
        category:"shirt",
        occucation:"Men's",
        size:"X",
        best:false,
        price:"34",
        oldPrice:"$170",
        title:"Half solder T-shirt in best price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (2).jpeg",
        off:"30% off",
    },
    {
        id:5,
        rate:4.8,
        color:"Blue",
        rated_Person:20234,
        category:"shirt",
        occucation:"Weddings",
        size:"S",
        best:false,
        price:"90",
        oldPrice:"$123",
        title:"Levis Shirt American Standard.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (3).jpeg",
        off:"20% off",
    }, 
    {
        id:6,
        rate:3.8,
        color:"Blue",
        rated_Person:2001,
        category:"shirt",
        occucation:"Dress",
        size:"L",
        best:false,
        price:"28",
        oldPrice:"$43",
        title:"Wedding Shirts in Lightblue Color.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (4).jpeg",
        off:"40% off",
    },
    {
        id:7,
        rate:4.2,
        color:"Gold",
        rated_Person:1004,
        category:"t-shirt",
        occucation:"Men's",
        size:"S",
        best:true,
        price:"90",
        oldPrice:"$123",
        title:"Levis Shirt American Standard.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (5).jpeg",
        off:"19% off",
    }, 
    {
        id:8,
        rate:4.0,
        color:"Blue",
        rated_Person:124,
        category:"t-shirt",
        occucation:"Weddings",
        best:false,
        price:"30",
        oldPrice:"$73",
        title:"Levis Shirt in Combo Color.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (6).jpeg",
        off:"24% off",
    }, 
    {
        id:9,
        rate:4.4,
        color:"Gray",
        rated_Person:12340,
        category:"t-shirt",
        occucation:"Weddings",
        size:"M",
        best:false,
        price:"30",
        oldPrice:"$73",
        title:"t-Shirt maded in gray Color.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (7).jpeg",
        off:"32% off",
    }, 
    {
        id:10,
        rate:4.4,
        color:"Black",
        rated_Person:12340,
        category:"pants",
        occucation:"Women",
        size:"XL",
        best:true,
        price:"30",
        oldPrice:"$73",
        title:"Cargo Pant made in India.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (21).jpeg",
        off:"32% off",
    }, 
    {
        id:11,
        rate:4.1,
        color:"White",
        rated_Person:124,
        category:"pants",
        occucation:"Men's",
        size:"S",
        best:false,
        price:"65",
        oldPrice:"$93",
        title:" Pant made in India.",
        description:"Lymica Cargo Pants .",
        img:"/images/AllImages/images (22).jpeg",
        off:"39% off",
    }, 
    {
        id:12,
        rate:3.9,
        color:"Gray",
        rated_Person:120,
        category:"jeans",
        occucation:"Dress",
        size:"X",
        best:true,
        price:"205",
        oldPrice:"$313",
        title:"Lather Jeans made in India.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (23).jpeg",
        off:"22% off",
    }, 
    {
        id:13,
        rate:4.1,
        color:"White",
        rated_Person:1230,
        category:"shirt",
        occucation:"Weddings",
        size:"M",
        best:true,
        price:"55",
        oldPrice:"$73",
        title:"Shirt White and Gray color Mixture .",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (27).jpeg",
        off:"19% off",
    }, 
    {
        id:14,
        rate:4.1,
        color:"White",
        rated_Person:1230,
        category:"jeans",
        occucation:"Women",
        size:"X",
        best:true,
        price:"85",
        oldPrice:"$123",
        title:"Cargo Jeans in Your Price .",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (30).jpeg",
        off:"29% off",
    }, 
    {
        id:15,
        rate:3.1,
        color:"Blue",
        rated_Person:230,
        category:"t-shirt",
        occucation:"Men's",
        size:"L",
        best:false,
        price:212,
        oldPrice:"$303",
        title:"Nivia T-shirt Cotton Mixture .",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (8).jpeg",
        off:"24% off",
    }, 
    {
        id:16,
        rate:4.1,
        color:"Gold",
        rated_Person:230,
        category:"t-shirt",
        occucation:"Men's",
        size:"M",
        best:true,
        price:"123",
        oldPrice:"$173",
        title:"T-shirt Cotton Mixture .",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (16).jpeg",
        off:"34% off",
    }, 
    {
        id:17,
        rate:4.1,
        color:"Blue",
        rated_Person:2130,
        category:"jeans",
        occucation:"Men's",
        size:"S",
        best:true,
        price:162,
        oldPrice:"$153",
        title:"Best Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (36).jpeg",
        off:"24% off",
    }, 
    {
        id:18,
        rate:4.4,
        color:"Blue",
        rated_Person:40,
        category:"t-shirt",
        occucation:"Men's",
        size:"S",
        best:true,
        price:"30",
        oldPrice:"$73",
        title:"t-Shirt maded in blue Color.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (17).jpeg",
        off:"32% off",
    }, 
    {
        id:19,
        rate:3.8,
        color:"Blue",
        rated_Person:130,
        category:"shirt",
        occucation:"Weddings",
        size:"X",
        best:false,
        price:"55",
        oldPrice:"$83",
        title:"Shirt White and blue color Mixture .",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (29).jpeg",
        off:"31% off",
    }, 
    {
        id:20,
        rate:4.4,
        color:"Blue",
        rated_Person:2110,
        category:"jeans",
        occucation:"Weddings",
        size:"S",
        best:true,
        price:"80",
        oldPrice:"$123",
        title:"Groser Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (31).jpeg",
        off:"19% off",
    }, 
    {
        id:21,
        rate:4.4,
        color:"Blue",
        rated_Person:210,
        category:"jeans",
        occucation:"Dress",
        size:"M",
        best:false,
        price:"43",
        oldPrice:"$103",
        title:"Carousel Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (32).jpeg",
        off:"29% off",
    }, 
    {
        id:22,
        rate:3.4,
        color:"White",
        rated_Person:40,
        category:"t-shirt",
        occucation:"Dress",
        size:"L",
        best:false,
        price:"40",
        oldPrice:"$73",
        title:"white t-shirt maded in price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (9).jpeg",
        off:"31% off",
    }, 
    {
        id:23,
        rate:4.4,
        color:"Blue",
        rated_Person:219,
        category:"pants",
        occucation:"Weddings",
        size:"S",
        best:true,
        price:"80",
        oldPrice:"$123",
        title:"Groser Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (35).jpeg",
        off:"19% off",
    }, 
    {
        id:24,
        rate:4.2,
        color:"White",
        rated_Person:2129,
        category:"pants",
        occucation:"Men's",
        size:"S",
        best:false,
        price:"110",
        oldPrice:"$163",
        title:"Cargo Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (26).jpeg",
        off:"23% off",
    }, 
    {
        id:25,
        rate:3.2,
        color:"White",
        rated_Person:2239,
        category:"pants",
        occucation:"Weddings",
        size:"X",
        best:false,
        price:"114",
        oldPrice:"$153",
        title:"Trouser Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (25).jpeg",
        off:"29% off",
    }, 
    {
        id:26,
        rate:3.4,
        color:"Black",
        rated_Person:4300,
        category:"t-shirt",
        occucation:"Women",
        size:"S",
        best:true,
        price:"40",
        oldPrice:"$83",
        title:"Black t-shirt maded in price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (19).jpeg",
        off:"51% off",
    }, 
    {
        id:27,
        rate:2.4,
        color:"Black",
        rated_Person:4130,
        category:"t-shirt",
        occucation:"Weddings",
        size:"L",
        best:false,
        price:"20",
        oldPrice:"$33",
        title:"white t-shirt maded in price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (18).jpeg",
        off:"21% off",
    }, 
    {
        id:28,
        rate:4.4,
        color:"White",
        rated_Person:430,
        category:"t-shirt",
        occucation:"Men's",
        size:"S",
        best:true,
        price:"20",
        oldPrice:"$33",
        title:"white t-shirt maded in price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (14).jpeg",
        off:"23% off",
    }, 
    {
        id:29,
        rate:4.2,
        color:"Gold",
        rated_Person:430,
        category:"t-shirt",
        occucation:"Dress",
        size:"S",
        best:false,
        price:"20",
        oldPrice:"$33",
        title:"Golden Yellow Color t-shirt.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (12).jpeg",
        off:"23% off",
    }, 
    {
        id:30,
        rate:4.4,
        color:"Blue",
        rated_Person:210,
        category:"jeans",
        occucation:"Weddings",
        size:"M",
        best:true,
        price:"43",
        oldPrice:"$103",
        title:"Carousel Jeans in Price.",
        description:"Lymica Cargo Pants  ",
        img:"/images/AllImages/images (33).jpeg",
        off:"29% off",
    }, 
];

export default AllCartsApi;